export const array_ban_can=[
    {
        id:1,
        text:'Ban',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:2,
        text:'Bán',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:3,
        text:'Bàn',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:4,
        text:'Bãn',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:5,
        text:'Bản',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:6,
        text:'Bạn',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },    
    {
        id:7,
        text:'Can',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:8,
        text:'Cán',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:9,
        text:'Càn',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:10,
        text:'Cản',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:11,
        text:'Cạn',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },

]