export const array_han_lan=[
    {
        id:1,
        text:'Han',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:2,
        text:'Hán',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:3,
        text:'Hàn',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:4,
        text:'Hãn',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:5,
        text:'Hản',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:6,
        text:'Hạn',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },    
    {
        id:7,
        text:'Lan',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:8,
        text:'Lán',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:9,
        text:'Làn',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
]