export const ban_can=[
    {
        id:1,
        text:'Van',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:2,
        text:'Ván',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:3,
        text:'Vàn',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:4,
        text:'Vãn',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:5,
        text:'Vản',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:6,
        text:'Vạn',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },    
    {
        id:7,
        text:'Quan',
        audio:'',
        phonetics:'',
        translate:''
    },
    {
        id:8,
        text:'Quán',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:9,
        text:'Quản',
        audio:'',
        phonetics:'',
        translate:''
    },

]