export const array_san_tan=[
    {
        id:1,
        text:'San',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:2,
        text:'Sán',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:3,
        text:'Sàn',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:4,
        text:'Sãn',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:5,
        text:'Sản',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:6,
        text:'Sạn',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },    
    {
        id:7,
        text:'Tan',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:8,
        text:'Tán',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:9,
        text:'Tàn',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:10,
        text:'Tản',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:11,
        text:'Tạn',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },

]