import chineseaudio from "../../../../assets/sounds/lesson_1_1/chinese.mp3"
export const array_b_x_m=[
    {
        id:1,
        text:'Bam',
        audio:chineseaudio,
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:2,
        text:'Bám',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:3,
        text:'Cam',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:4,
        text:'Cám',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:5,
        text:'Cảm',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:6,
        text:'Cạm',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },    
    {
        id:7,
        text:'Ham',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:8,
        text:'Hám',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:9,
        text:'Hàm',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:10,
        text:'Hãm',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:11,
        text:'Lam',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:12,
        text:'Làm',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:13,
        text:'Lạm',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:14,
        text:'Nam',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:15,
        text:'Nám',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:16,
        text:'Nạm',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:17,
        text:'Sam',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:18,
        text:'Sám',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:19,
        text:'Sàm',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:20,
        text:'Sạm',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:21,
        text:'Tam',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:22,
        text:'Tám',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:23,
        text:'Tàm',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:24,
        text:'Tạm',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:25,
        text:'Xam',
        audio:'',
        phonetics:'',
        translate:''
    },
    {
        id:26,
        text:'Xám',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:27,
        text:'Xàm',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:28,
        text:'Xạm',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
]