export const array_nh_ng=[
    {
        id:1,
        text:'Nha',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:2,
        text:'Nho',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:3,
        text:'Nhô',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:4,
        text:'Nhu',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:5,
        text:'Nga',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:6,
        text:'Ngo',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:7,
        text:'Ngô',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
    {
        id:8,
        text:'Ngu',
        audio:'',
        phonetics:'',
        vietnamese:'',
        english:''
    },
]